q2 : all
	gcc -g q2.c sqlite.c -lpthread -ldl
q3 :
	gcc -g q3.c sqlite.c -lpthread -ldl
q4 :
	gcc -g q4.c sqlite.c -lpthread -ldl -lm
q5 :
	gcc -g q5.c sqlite.c -lpthread -ldl -lm
q6 :
	gcc -g q6.c sqlite.c -lpthread -ldl
q7 :
	gcc -g q7.c sqlite.c -lpthread -ldl
q8 :
	gcc -g q8.c sqlite.c -lpthread -ldl
q9 :
	gcc -g q9.c sqlite.c -lpthread -ldl
all :
	gcc -g *.c sqlite.c -lpthread -ldl -lm

clean :
	rm a.out a.out.*